keywords = "Linux, FreeBSD, howto, Ubuntu, Arch, tech news, HD, app review, Systems, Network, Sysadmin, netsec, Politics, development, podcast, Linux Action Show, TechSNAP, SciByte, FauxShow, Coder Radio, LIVE stream, Bitcoin, PlanB, BSDNow"
description = "Independent coverage of Linux, BSD, Open Source, System Administration, Information Security, News, Software Development and Discussion."
author = "Jupiter Broadcasting"
ogimage = "/images/jupiter-broadcasting.png" # Open Graph default image

# itunes feed info
feed.copyright = "Copyright 2022 Jupiter Broadcasting" #do not use markdown in this field; it is used in the feed
feed.itunes_subtitle = "A weekly talk show" #no markdown or HTML
feed.itunes_author = "Jupiter Broadcasting" #no markdown or HTML
feed.itunes_summary = "A weekly talk show" # Limited to 4000 characters or less, plain text, no HTML
feed.itunes_owner_name = "Jupiter Broadcasting"
feed.itunes_owner_email = "chris@jupiterbroadcasting.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
feed.itunes_image = "https://jb.codefighters.net/images/logo_narrow.png" #fqdn to the image art for your podcast
feed.itunes_top_category = "Education"
feed.itunes_first_sub_category = "How To"
feed.itunes_second_sub_category = "Business"
feed.language = "en-us"
feed.itunes_type = "episodic"
# based on issue 162
feed.rss = "http://feeds2.feedburner.com/JupiterBroadcasting"
feed.video_rss = "http://feeds2.feedburner.com/AllJupiterVideos"

# Calendar
calendar.rss = "https://www.google.com/calendar/ical/jalb5frk4cunnaedbfemuqbhv4@group.calendar.google.com/public/basic.ics"
calendar.embedd= "jalb5frk4cunnaedbfemuqbhv4@group.calendar.google.com"

analytics = "https://plausible.ktz.cloud/js/plausible.js"

github_repo = "https://github.com/JupiterBroadcasting/jupiterbroadcasting.com" 

# Sponsor Page
sponsors.lookbackdays = -90