name: E2E Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run hugo build
        uses: jakejarvis/hugo-build-action@master 
        with:
          args: --gc --config ./config.toml
      - name: run server
        run: |
          cd public && python -m http.server 1313 &
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        working-directory: ./test
        run: |
          python -m pip install --upgrade pip
          pip install -r local-requirements.txt
          pip install -e .
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: Run your tests
        working-directory: ./test
        run: pytest --base-url http://localhost:1313 e2e/*
      - name: Save screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: test/screenshots/