name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy-jb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --gc --config ./config.toml
    - uses: burnett01/rsync-deployments@4.1
      with:
       switches: -avzr --delete
       path: ./public/
       remote_path: /var/www/jupiterbroadcasting.net
       remote_host: ${{ secrets.DEPLOY_HOST }}
       remote_port: ${{ secrets.DEPLOY_PORT }}
       remote_user: ${{ secrets.DEPLOY_USER }}
       remote_key: ${{ secrets.DEPLOY_KEY }}